#!/usr/bin/env bash
# Redirection
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee "/var/www/html/index.nginx-debian.html"
new_string="server_name _;\n\t\trewrite /redirect_me https://www.youtube.com/watch?v=SMaVii7nnj4 permanent;"
sudo sed -i 's/server_name _;/'"$new_string"'/' /etc/nginx/sites-enabled/default
sudo service nginx restart
