#!/usr/bin/env bash
# Not found page 404
sudo apt-get update
sudo apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
new_string="server_name _;\n\t\trewrite /redirect_me https://www.youtube.com/watch?v=SMaVii7nnj4 permanent;\n\t\terror_page 404 /404.html;\n"
sed -i 's|server_name _;|'"$new_string"'|' /etc/nginx/sites-enabled/default
sudo service nginx restart
