#!/usr/bin/env bash
# Install nginx and update default server configuracion
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > '/var/www/html/index.nginx-debian.html'
echo "Ceci n'est pas une page" > /var/www/html/404.html
new_redirect="server_name _;\n\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\terror_page 404 /404.html;\n\tadd_header X-Served-By $HOSTNAME;\n"
sed -i 's|server_name _;|'"$new_redirect"'|' /etc/nginx/sites-enabled/default
sudo service nginx restart
