#!/usr/bin/env bash
# Double the number of webservers
apt-get -y update
apt-get -y install nginx
sudo sed -i "44i \tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-enabled/default
service nginx restart
