#!/usr/bin/env bash
# Double the number of webservers
apt-get -y update
apt-get -y install nginx
new_string="server_name _;\n\t\trewrite /redirect_me https://www.youtube.com/watch?v=SMaVii7nnj4 permanent;\n\ttadd_header X-Server-By $(hostname);"
sudo sed -i 's|server_name _;|'"$new_string"'|' /etc/nginx/sites-enabled/default
service nginx restart
