#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server
apt-get -y update
apt-get -y install haproxy=1.5

sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
redirection="frontend firstbalance\n\tbind *:80\n\tmode http\n\tdefault_backend webservers\n\nbackend webservers\n\tbalance roundrobin\n\tserver web-01 34.75.246.108:80 check\n\tserver web-02 34.74.204.253:80 check\n"
echo -e "$redirection" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
