#!/usr/bin/env bash
# Process and PID file
echo $$ >> /var/run/holbertonscript.pid
trap 'echo I hate the kill command; sudo rm $file; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'sudo rm $file; exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done