#!/usr/bin/env bash
# If 9, say Hi!
TEXT0="Holberton School"
TEXT1="Hi"
i=0
while [ $i -le 9 ]
do
    i=$(( i + 1 ))
    if [ $i != 9 ]
    then
        echo "$TEXT0"
    else
        echo "$TEXT1"
    fi
done
