#!/usr/bin/env bash
# 4 bad luck, 8 is your chance
i=0
while [ $i -le 9 ]
do
    i=$(( i + 1 ))
    if [ $i == 4 ]
    then
        echo "bad luck"
    elif [ $i == 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
done
